In [1]:
import numpy as np
import pandas as pd

a = np.array([1,2,5])
print("a", a)

b = np.array([[1,2,3],[4,5,6]])
print("b",b)

A = np.arange(0,9).reshape(3,3)
print("A",A)
B = np.ones((3,3))
print("B",B)
np.dot(A,B)

se1 = pd.Series([12,-4,7,9])

print(se1)

n_s = np.linspace(0.70, 0.85, num=15)
print("n_s",n_s)

#csvFrame = pd.read_csv("C:\\personalData\\bigdata\\survey_results_public\\survey_results_public.csv")

#print("csvFrame",csvFrame)

#print(csvFrame.columns)
#print(csvFrame.describe)








a [1 2 5]
b [[1 2 3]
 [4 5 6]]
A [[0 1 2]
 [3 4 5]
 [6 7 8]]
B [[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
0    12
1    -4
2     7
3     9
dtype: int64
n_s [ 0.7         0.71071429  0.72142857  0.73214286  0.74285714  0.75357143
  0.76428571  0.775       0.78571429  0.79642857  0.80714286  0.81785714
  0.82857143  0.83928571  0.85      ]


NameError: name 'csvFrame' is not defined